/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 13:50:29 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 13:50:29 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 13:50:29 +0000] [79] [INFO] Using worker: sync
[2025-08-10 13:50:29 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 13:50:29 +0000] [81] [INFO] Booting worker with pid: 81
[2025-08-10 13:50:31 +0000] [79] [INFO] Handling signal: term
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 13:57:13 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 13:57:13 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 13:57:13 +0000] [79] [INFO] Using worker: sync
[2025-08-10 13:57:13 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 13:57:13 +0000] [81] [INFO] Booting worker with pid: 81
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 10:58:07 -0300] [81] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:58:07 -0300] [81] [INFO] Worker exiting (pid: 81)
[2025-08-10 13:58:07 +0000] [269] [INFO] Booting worker with pid: 269
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 10:58:56 -0300] [80] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:58:56 -0300] [80] [INFO] Worker exiting (pid: 80)
[2025-08-10 13:58:56 +0000] [303] [INFO] Booting worker with pid: 303
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 10:59:29 -0300] [303] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:59:29 -0300] [303] [INFO] Worker exiting (pid: 303)
[2025-08-10 13:59:30 +0000] [337] [INFO] Booting worker with pid: 337
[2025-08-10 10:59:30 -0300] [269] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:59:30 -0300] [269] [INFO] Worker exiting (pid: 269)
[2025-08-10 13:59:31 +0000] [354] [INFO] Booting worker with pid: 354
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:04 -0300] [337] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:04 -0300] [337] [INFO] Worker exiting (pid: 337)
[2025-08-10 11:03:05 -0300] [354] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:05 -0300] [354] [INFO] Worker exiting (pid: 354)
[2025-08-10 14:03:05 +0000] [443] [INFO] Booting worker with pid: 443
[2025-08-10 14:03:05 +0000] [444] [INFO] Booting worker with pid: 444
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:12 -0300] [443] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:12 -0300] [443] [INFO] Worker exiting (pid: 443)
[2025-08-10 11:03:12 -0300] [444] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:12 -0300] [444] [INFO] Worker exiting (pid: 444)
[2025-08-10 14:03:13 +0000] [511] [INFO] Booting worker with pid: 511
[2025-08-10 14:03:13 +0000] [512] [INFO] Booting worker with pid: 512
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:15 -0300] [511] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 21, in <module>
    @receiver(post_save, sender=Organization)
NameError: name 'Organization' is not defined
[2025-08-10 11:03:15 -0300] [511] [INFO] Worker exiting (pid: 511)
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:15 -0300] [512] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 21, in <module>
    @receiver(post_save, sender=Organization)
NameError: name 'Organization' is not defined
[2025-08-10 11:03:15 -0300] [512] [INFO] Worker exiting (pid: 512)
[2025-08-10 14:03:15 +0000] [79] [WARNING] Worker with pid 512 was terminated due to signal 15
[2025-08-10 14:03:16 +0000] [79] [INFO] Shutting down: Master
[2025-08-10 14:03:16 +0000] [79] [INFO] Reason: Worker failed to boot.
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 14:03:17 +0000] [577] [INFO] Starting gunicorn 20.1.0
[2025-08-10 14:03:17 +0000] [577] [INFO] Listening at: http://0.0.0.0:8000 (577)
[2025-08-10 14:03:17 +0000] [577] [INFO] Using worker: sync
[2025-08-10 14:03:17 +0000] [578] [INFO] Booting worker with pid: 578
[2025-08-10 14:03:17 +0000] [579] [INFO] Booting worker with pid: 579
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:24 -0300] [578] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:24 -0300] [578] [INFO] Worker exiting (pid: 578)
[2025-08-10 11:03:24 -0300] [579] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:24 -0300] [579] [INFO] Worker exiting (pid: 579)
[2025-08-10 14:03:24 +0000] [646] [INFO] Booting worker with pid: 646
[2025-08-10 14:03:24 +0000] [647] [INFO] Booting worker with pid: 647
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:04:06 -0300] [646] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 11:04:06 -0300] [646] [INFO] Worker exiting (pid: 646)
[2025-08-10 11:04:06 -0300] [647] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 11:04:06 -0300] [647] [INFO] Worker exiting (pid: 647)
[2025-08-10 14:04:06 +0000] [714] [INFO] Booting worker with pid: 714
[2025-08-10 14:04:06 +0000] [715] [INFO] Booting worker with pid: 715
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 14:05:30 +0000] [577] [INFO] Handling signal: term
[2025-08-10 11:05:30 -0300] [715] [INFO] Worker exiting (pid: 715)
[2025-08-10 11:05:30 -0300] [714] [INFO] Worker exiting (pid: 714)
[2025-08-10 14:05:31 +0000] [577] [INFO] Shutting down: Master
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 14:10:26 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 14:10:26 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 14:10:26 +0000] [79] [INFO] Using worker: sync
[2025-08-10 14:10:26 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 14:10:26 +0000] [81] [INFO] Booting worker with pid: 81
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 14:14:26 +0000] [79] [INFO] Handling signal: term
[2025-08-10 11:14:26 -0300] [81] [INFO] Worker exiting (pid: 81)
[2025-08-10 11:14:26 -0300] [80] [INFO] Worker exiting (pid: 80)
[2025-08-10 14:14:26 +0000] [79] [INFO] Shutting down: Master
